Es6
josuerushanika/Awesome-Books-ES6 pull request #1
Opened 2023-01-23 19:53 UTC by josuerushanika

In this project, l restructure my  Awesome books app code. The goal is to make it more organized by using modules. I also practice the ES6.

**Project requirements**

_Use ES6 syntax._
Divide my code into modules. Save each module in a separate file in the modules dir. Import modules in the index.js file.
Refactor my  methods and functions to arrow functions.
Use let and const in a correct way.

_Display the current date below the navigation bar._

I used a library [Luxon](https://moment.github.io/luxon/#/install?id=es6)

_Project overview_

![image](https://user-images.githubusercontent.com/100031798/214136109-8184cf1f-08d1-4d32-a6aa-856a121cc9af.png)

2023-01-23 20:24 UTC, vickymarz requested changes
Hi @josuerushanika, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 20:24 UTC, victorokoroji commented on modules/navigation.js
> +// export default navLink;
- [ ] KIndly remove all commented code from your code base so that your code will be clean  and readable

2023-01-23 21:07 UTC, josuerushanika commented on modules/navigation.js
> +// export default navLink;
Thx it is fixed

2023-01-23 21:27 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @josuerushanika ✔️, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media0.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 21:58 UTC, merged

2023-07-28 22:12 UTC, josuerushanika commented
Thank You